#!/bin/bash

# ---
# TRAINING
# ---

export LOSS="categorical_cross_entropy"

export TRAIN_EPOCHS=3
export BATCH_SIZE=30
export LEARNING_RATE=3.0

export MOMENTUM_FACTOR=0.25

export LOG_STEP_COUNT_STEPS=20000  # monitor thoroughly
export SAVE_CHECKPOINT_STEP=60000  # once per epoch

### run training
./mnist


# ---
# EVALUATION && EXPORT
# ---
export SAVE_TRAIN_PREDICTIONS="trainPredictions"
export SAVE_TEST_PREDICTIONS="actualTestPredictions"

### run evaluation
./mnist-evaluate
