#!/bin/bash

# ---
# COMPILATION
# ---

tput setaf 2; echo "Configuring"; tput sgr0;

cmake . -DCMAKE_BUILD_TYPE=Release

tput setaf 2; echo "Building from source"; tput sgr0;

cmake --buld . --target all


# ---
# TRAINING
# ---

tput setaf 2; echo "Training"; tput sgr0;


export CONTINUE_TRAINING=0

export LOSS="categorical_cross_entropy" 

export TRAIN_EPOCHS=30
export BATCH_SIZE=30

export LEARNING_RATE=3.0
export MOMENTUM_FACTOR=0.25

export LOG_STEP_COUNT_STEPS=20000  # monitor thoroughly
export VALIDATE_STEP_COUNT_EPOCHS=5

export SAVE_CHECKPOINT_STEP=60000  # once per epoch
export KEEP_CHECKPOINTS_MAX=3

./mnist

if [ $? -ne 0 ]; then
	tput setaf 1; echo "Unexpected error occured during training."; tput sgr0;
	exit 42
fi


# ---
# EVALUATION && EXPORT
# ---

tput setaf 2; echo "Evaluation"; tput sgr0;

export SAVE_TRAIN_PREDICTIONS="trainPredictions"
export SAVE_TEST_PREDICTIONS="actualTestPredictions"

./mnist-evaluate
